version: '3'
services:
  service_2:
    build:
      context: ./service_2
    networks:
      - pk-sam
    ports:
      - "5003:5003"
    

  service_3:
    build:
      context: ./service_3
    networks:
      - pk-sam
    ports:
      - "5004:5004"


networks:
  pk-sam:
    name: pk-sam
    external: true
  